Add js lint fixer hook

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -30,4 +30,25 @@ fi
 
 echo "php-cs-fixer pre commit hook success"
 
+echo "eslint pre commit hook start"
+
+ESLINT="node_modules/.bin/eslint"
+
+if [ -x node_modules/.bin/eslint ]; then
+    git status --porcelain | grep -e '^[AM]\(.*\).\([jt]sx\?\)$' | cut -c 3- | while read line; do
+        $ESLINT --fix "$line";
+        git add "$line";
+    done
+else
+    echo ""
+    echo "Eslint not found, please install it by running:"
+    echo ""
+    echo "  yarn install"
+    echo ""
+    echo "eslint pre commit hook abort"
+    exit 1
+fi
+
+echo "eslint pre commit hook success"
+
 exit 0
